general:
    artifacts:
        - /home/ubuntu/GrpcEample/app/build/outputs/apk/

machine:
    environment:
        ANDROID_HOME: /usr/local/android-sdk-linux

dependencies:
    pre:
        - wget "https://services.gradle.org/distributions/gradle-4.0.1-bin.zip"; unzip gradle-4.0.1-bin.zip
        - source environmentSetup.sh && copyEnvVarsToGradleProperties
    override:
        - cp -r licenses/. $ANDROID_HOME/licenses
        - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
        - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
        - echo y | android update sdk --no-ui --all --filter tools,platform-tools,build-tools-25.0.3,android-25,extra-google-m2repository,extra-google-google_play_services,extra-android-m2repository
        - ANDROID_HOME=/usr/local/android-sdk-linux ./gradlew dependencies
checkout:
    post:
      - cp -r licenses/. $ANDROID_HOME/licenses
test:
    override:
        # start the build
        - (./gradlew assemble):
            timeout: 360
        # start the emulator
        - emulator -avd circleci-android22 -no-audio -no-window:
            background: true
            parallel: true
        # wait for it to have booted
        - circle-android wait-for-boot
        # unlock the emulator screen
        - sleep 30
        - adb shell input keyevent 82
        # run tests  against the emulator.
        - ./gradlew connectedDevelopmentDebugAndroidTest -PdisablePreDex
        # copy the build outputs to artifacts
        - cp -r app/build/outputs $CIRCLE_ARTIFACTS
        # copy the test results to the test results directory.
        - cp -r app/build/outputs/androidTest-results/* $CIRCLE_TEST_REPORTS
