version: 2
jobs:
  build:
    docker:
      - image: lakoo/android-ndk:25-25.0.3-r14b
    environment:
      TERM: dumb
      GRADLE_OPTS: '-Dorg.gradle.jvmargs="-Xmx1560m -XX:+HeapDumpOnOutOfMemoryError" -Dorg.gradle.daemon=false'
    steps:
      - checkout
      - run:
          name: Set Up Env
          command: source environmentSetup.sh && copyEnvVarsToGradleProperties
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}

      - save_cache:
          paths: ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Run Lint
          command: ./gradlew lint
      - run:
          name: Run Unit Tests
          command: |
            ./gradlew testDebugUnitTest --tests "example.grpc.*"
      - run:
          name: Run pitest
          command: |
            ./gradlew pitest
      - store_test_results:
          path: app/build/test-results
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_artifacts:
          path: app/build/reports/pitest/debug/*
      - store_artifacts:
          path: app/build/outputs/apk
          destination: apks
